FROM node:11-alpine

COPY . /app
WORKDIR /app

RUN cd client && \
  npm install && \
  npm run build && \
  cd .. && \
  cd server && \
  npm install && \
  npm run build && \
  npm prune --production

WORKDIR /app/server/build/server/src
EXPOSE 5000
ENV NODE_ENV production
ENTRYPOINT [ "node", "server.js" ]
